export const COPY = {
  brand: {
    town: "TownNet",
    nyc: "N.Y.C.",
    aria: "TownNet N.Y.C.",
    homeAria: "TownNet N.Y.C. home",
  },
  hero: {
    description:
      "TownNet N.Y.C. connects residents, caseworkers, and community organizations to nearby food, health, housing, legal, job, youth, senior, and civic services — all in one warm, citywide discovery layer.",
    title: "Find your way to a better life in New York",
    getStarted: "Get started",
    viewMap: "View map",
  },
  scout: {
    mascotAlt: "Scout, a friendly goldendoodle mascot",
    title: "Hi, I'm Scout.",
    prompt: "Describe what you're looking for and I'll find what fits.",
    inputPlaceholder: "e.g. I'm 68, live in the Bronx, and need help with groceries…",
    sendAria: "Send to Scout",
    divider: "or choose how to start",
    servicesButton: "I need services",
    volunteerButton: "I want to volunteer",
    mapButton: "Explore the map",
  },
  map: {
    title: "Find services near you",
    subtitle: "Search city programs, nonprofits, and community services across New York City.",
    searchPlaceholder: "Search programs, services, or organizations…",
    zipPlaceholder: "ZIP code",
    searchButton: "Search",
    categoryAria: "Service categories",
    mapResultsAria: "Map and program results",
    mapPlaceholder: "Map coming in Phase 4 — Mapbox integration",
    sidebarAria: "Sample program results",
    verified: "Verified",
    nextStep: "Take the next step",
    closeDetail: "Close program details",
  },
  categories: [
    { key: "food", label: "Food", color: "#e74c3c" },
    { key: "health", label: "Health", color: "#3498db" },
    { key: "housing", label: "Housing", color: "#9b59b6" },
    { key: "legal", label: "Legal", color: "#e67e22" },
    { key: "jobs", label: "Jobs", color: "#f39c12" },
    { key: "seniors", label: "Seniors", color: "#1abc9c" },
    { key: "youth", label: "Youth", color: "#2ecc71" },
    { key: "volunteer", label: "Volunteer", color: "#e91e63" },
  ],
  programs: [
    {
      id: "bronxworks-food-pantry",
      name: "Food Pantry",
      fullName: "BronxWorks Food Pantry",
      organization: "BronxWorks",
      organizationVerified: true,
      category: "Food",
      categoryKey: "food",
      distance: "0.3 mi",
      borough: "Bronx",
      description: "Free groceries and hot meals, no eligibility required.",
      cost: "Free",
      hours: "Mon–Fri, 9:00 AM–5:00 PM",
      languages: "English, Spanish",
      eligibility: "Open to all New Yorkers. No appointment required.",
      address: "1130 Grand Concourse, Bronx, NY 10456",
    },
    {
      id: "nyc-aging-senior-center",
      name: "Senior Center",
      fullName: "NYC Aging Senior Center",
      organization: "NYC Aging",
      organizationVerified: true,
      category: "Seniors",
      categoryKey: "seniors",
      distance: "0.6 mi",
      borough: "Bronx",
      description: "Daily activities, fitness, and hot lunch for adults 60+.",
      cost: "Free",
      hours: "Mon–Fri, 8:30 AM–4:30 PM",
      languages: "English, Spanish, Bengali",
      eligibility: "Adults 60+ and their caregivers.",
      address: "Neighborhood senior center, Bronx, NY",
    },
    {
      id: "workforce1-career-center",
      name: "Career Center",
      fullName: "Workforce1 Career Center",
      organization: "Workforce1",
      organizationVerified: true,
      category: "Jobs",
      categoryKey: "jobs",
      distance: "1.1 mi",
      borough: "Bronx",
      description: "Free job placement and resume help for NYC residents.",
      cost: "Free",
      hours: "Mon–Fri, 9:00 AM–5:00 PM",
      languages: "English, Spanish",
      eligibility: "NYC residents ages 18+.",
      address: "Workforce1 Bronx Career Center, Bronx, NY",
    },
    {
      id: "legal-aid-society",
      name: "Civil Legal Help",
      fullName: "Legal Aid Society",
      organization: "The Legal Aid Society",
      organizationVerified: true,
      category: "Legal",
      categoryKey: "legal",
      distance: "1.4 mi",
      borough: "Bronx",
      description: "Free legal services for low-income New Yorkers.",
      cost: "Free or Low-cost",
      hours: "Mon–Fri, 9:00 AM–5:00 PM",
      languages: "English, Spanish, interpretation available",
      eligibility: "Low-income New Yorkers. Screening may be required.",
      address: "Bronx legal services office, Bronx, NY",
    },
  ],

  intake: {
    modes: {
      default: {
        steps: [
          "Hi! I'm Scout. To find the best matches for you, I have a few quick questions. First — what neighborhood or ZIP code are you in?",
          "Got it! And roughly how old are you? You can say a range like 'in my 60s' or just skip this if you prefer.",
          "What do you need help with? You can describe it in your own words — like 'groceries and rent help' or 'job training' or 'something for my kids after school'.",
          "One last thing — do you prefer services in any language other than English?",
        ],
        skipLabel: "Skip",
        languageSkipLabel: "English is fine",
        loading: "Give me a moment to find what fits you best…",
        resultsHeading: "Here's what Scout found for you",
        resultButton: "Take the next step",
        resetPrefix: "Not seeing what you need? ",
        resetLink: "Try describing it differently",
        results: [
          {
            category: "Food",
            categoryKey: "food",
            name: "BronxWorks Food Pantry",
            organization: "BronxWorks",
            why: "Matches your ZIP and has no eligibility requirements",
            distance: "0.3 mi",
          },
          {
            category: "Housing",
            categoryKey: "housing",
            name: "NYC HRA Emergency Assistance",
            organization: "NYC Human Resources Administration",
            why: "Available to all NYC residents facing housing instability",
            distance: "0.6 mi",
          },
          {
            category: "Health",
            categoryKey: "health",
            name: "Montefiore Community Health Center",
            organization: "Montefiore Health System",
            why: "Offers services in multiple languages near you",
            distance: "0.8 mi",
          },
          {
            category: "Jobs",
            categoryKey: "jobs",
            name: "Workforce1 Career Center",
            organization: "Workforce1",
            why: "Free job placement for all NYC residents",
            distance: "1.1 mi",
          },
        ],
      },
      volunteer: {
        steps: [
          "Hi! I'm Scout. To find the best matches for you, I have a few quick questions. First — what neighborhood or ZIP code are you in?",
          "What kind of volunteering interests you? For example — working with kids, helping seniors, food distribution, legal support, community events.",
          "How much time can you give? A few hours a week, weekends, or are you flexible?",
          "Any language skills that might be useful?",
        ],
        skipLabel: "Skip",
        languageSkipLabel: "English is fine",
        loading: "Give me a moment to find what fits you best…",
        resultsHeading: "Here's what Scout found for you",
        resultButton: "Connect with this organization",
        resetPrefix: "Not seeing what you need? ",
        resetLink: "Try describing it differently",
        results: [
          {
            category: "Volunteer",
            categoryKey: "volunteer",
            name: "BronxWorks Volunteer Team",
            organization: "BronxWorks",
            why: "Food distribution shifts are available near your neighborhood",
            distance: "0.3 mi",
          },
          {
            category: "Seniors",
            categoryKey: "seniors",
            name: "Friendly Visiting Program",
            organization: "NYC Aging",
            why: "Great fit if you want to support older adults on a flexible schedule",
            distance: "0.6 mi",
          },
          {
            category: "Youth",
            categoryKey: "youth",
            name: "After-School Mentor Circle",
            organization: "Community Youth Partnership",
            why: "Connects volunteers with kids and after-school activities",
            distance: "0.9 mi",
          },
          {
            category: "Legal",
            categoryKey: "legal",
            name: "Community Legal Clinic Support",
            organization: "The Legal Aid Society",
            why: "Uses language and admin skills to support legal aid events",
            distance: "1.4 mi",
          },
        ],
      },
    },
    inputPlaceholder: "Type your answer…",
    sendAria: "Send answer to Scout",
  },
  detail: {
    summaryAria: "Program summary",
    detailsAria: "Program details",
    rows: {
      hours: "Hours",
      languages: "Languages",
      eligibility: "Eligibility",
      address: "Address",
    },
  },
  listOrg: {
    title: "Add your organization",
    subtitle: "Free for all verified nonprofits and community organizations",
    fields: {
      organizationName: "Organization name",
      mission: "Mission",
      focusAreas: "Focus areas",
      boroughsServed: "Boroughs served",
      languagesOffered: "Languages offered",
      hours: "Hours",
      website: "Website",
      contactEmail: "Contact email",
      phoneNumber: "Phone number",
    },
    boroughs: ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"],
    submit: "Submit for review",
    reviewNote:
      "We verify 501(c)(3) status or city contract before listing. Usually reviewed within 3 business days.",
  },
  comingSoon: {
    title: "coming soon",
    intake: "Intake",
    back: "Back to get started",
  },
  footer: {
    links: ["Español", "中文", "Русский", "About", "Accessibility", "For nonprofits"],
  },
};
